baseURL = "https://example.com/"
# include content marked as draft
buildDrafts = true
# include content with publishdate in the future
buildFuture = true
# include content already expired
buildExpired = true
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Zero MC"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Zeroshot and Orangemn6"
  email = "john.doe@example.com"
  description = "Landing Page for Zeroshot's site"
  bio = "First Row.  \nSecond Row."
  avatar = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    github = "https://github.com/jdoe"
    instagram = "https://instagram.com/jdoe"
    twitter = "https://twitter.com/jdoe"
    ello = ""
